language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

addons:
  chrome: stable

script:
  - npm run build

deploy:
  provider: s3
  access_key_id: "AKIAIROOOYQL2RYRPHHA"
  secret_access_key: 
    secure: "ESEKtHAWZ3IA1/v2UThAUDAyaS4Ti120MUU0sd4AzFXOCt/uM94EFKkNZ0ZsB/z46aAeeGZ25syWYI8Hx/lC0AZGfxgH+lKXkirQvd5AI8Ibp/Ofonx+xNPojkHOZrLcn04yvOBeNcH0OYEBASd31GCRFviSdQUWH9mB0V2oeKs+ICb0fkzKfN56NU0HxbaGmJ3jD3iiqQd81w2/PSzMODzC4E8coXBIXsjiFlOyV2bm44cYepweouSZSbzmNMIgS52ZQ8+E/9JxfdtVttnzzhbqtPVxw8NvXXMY6yFMUbwwpkObEaA2ueGc8kZZCTUr2yjzBv7/rmzl1TcGi9E22N/uYxuoSTIvLqNeq4Lg7Lr4+XEhXdplvuM08yZqITwL/si+u49LEcJctNQBushHAzrkcJYJ4+hccTIi9F33wJ4/LJ+z+SpzsIsTZ1p2ymeJ7p21xA5axsgLyNyKIgED5cSnH36oDXh1Lw53CyLeo5VMNJeB/w/MZkeJz2xxO6EIB5E3wtb1601sJPDHXlLRUFUlrL5JuIj+rhKT4rnyD/ovWHp+CDNP+wKjDaOLeAG+/vagr9nVYScqRAYpfPJMHN3lsyKz32E4FrDnixGaRL6YrlqlBI2LpUDW/AK8GYL7qiP91tjzurstPCA+/a5MXfoAlmaPseJS3TA60hx3kKA="
  bucket: "www.cucuyo.us"
  region: us-east-2
  skip_cleanup: true
  acl: public_read
