language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

addons:
  chrome: stable

script:
  - npm run build

deploy:
  provider: s3
  access_key_id: "AKIAIROOOYQL2RYRPHHA"
  secret_access_key:
    secure:"secure: "r4+/A2p4+M2PhpbGsjWosKOshsd1WaD/uv1LJgtupJ75R5D22xBPrsXqopqDAzdG9dUfatUuI39Re3mCQTggh6ZuLzcipntDDofvpkMS/rWlI5gLGIn3bUZ3mstcw0LGJQRJB3Z2Xx7GVePWQNVeBlk441vcVb5MhT2tJxNxeGwWECactLK+iPC0RyAFtf1SOCgagzbfBCdvwNbXhR1M5yqF2Zzfci/LrqRSjqKxHfOjwpcSqtG8mR8XW2NXBGZmX0xzxtLWxfdahnq8LsTW3Q8Ozw9RtysjK0XWjhU52DCsPSXdcJyad5CKZ+VOyOFcDmrO9hKNSRdDlGD59ARHxAWAL2QE3W7jJUm+8XSR26De33PGFwEijcdRqgoIeC2cskxJbV0I+D78apfRCBYgpnAewUijBTcfAOgX3rk7YAztJnNoBeEzpoRUcyBN3v6yhlpfpPRtBY41lsRUBCLwZieiCVA0UXPyNjicWieWLaI2tnJEDBClg7i7CWYtWoUo0mr6Tk9pv0NwH1Bzk8kQdBZ0fSCIBIE1l4KTyoDCwRZH4cvO1QzDu7SsvwkskK70sPBjzki63qPWJjuaUbZtcUSIo0qJaauHC8kQeolMVpqmVncSWDv6MlvjbL7p1daJr43ri1jASatrZboVRSunet8cJf7yha1cwlSt7gV2+N4="
  bucket: "S3 Bucket"